FROM continuumio/miniconda3:24.5.0-0
ADD ./requirements.dev.txt  /tmp/requirements.txt

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    build-essential gfortran libgdal-dev cmake gdb git vim curl ca-certificates lsb-release


RUN apt-get install ca-certificates curl
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
RUN chmod a+r /etc/apt/keyrings/docker.asc

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/debian $(lsb_release -cs) stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    docker-ce docker-ce-cli containerd.io docker-compose-plugin

ENV LANG pt_BR.UTF-8

RUN conda init bash
RUN conda create -n dev python=3.11
RUN echo "conda activate dev" >> ~/.bashrc
SHELL ["/bin/bash", "-c"]

RUN source ~/.bashrc && pip3 install --no-cache-dir -r /tmp/requirements.txt