FROM continuumio/miniconda3:4.12.0
ADD ./requirements.dev.txt  /tmp/requirements.txt

RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gfortran cmake vim
ENV LANG pt_BR.UTF-8

RUN conda init bash
RUN conda create -n dev python=3.8

SHELL ["conda", "run", "-n", "dev", "/bin/bash", "-c"]
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt
RUN echo "conda activate dev" >> ~/.bashrc