FROM continuumio/miniconda3:24.5.0-0

RUN apt-get update
RUN apt-get install -y --no-install-recommends libgfortran5 curl
ENV LANG pt_BR.UTF-8

RUN conda init bash
RUN conda create -n deploy python=3.11
RUN echo "conda activate deploy" >> ~/.bashrc
SHELL ["/bin/bash", "-c"]